//
//  ELGenerator+Product.m
//  MageDataCSVGenerator
//
//  Created by Eddie Luke Atmey on 06/12/17.
//  Copyright © 2017 EL. All rights reserved.
//

#import "ELGenerator+Product.h"

@implementation ELGenerator (Product)

#pragma mark - Mage1
+ (void)generateProduct
{
    for (NSInteger i = 20; i < 21; i++) {
        [self generateProduct:5000 forPage:i];
    }
}

+ (void)generateProduct:(NSInteger)total forPage:(NSInteger)page
{
    // Generate empty file
    NSString *fileName = [NSString stringWithFormat:@"product%02ld.csv", page];
    NSString *filePath = [self generateFileForName:fileName];

    CHCSVWriter *writer = [[CHCSVWriter alloc] initForWritingToCSVFile:filePath];
    [writer writeLineOfFields:@[@"sku",
                                @"_store",
                                @"_attribute_set",
                                @"_type",
                                @"_category",
                                @"_root_category",
                                @"_product_websites",
                                @"accessories_size",
                                @"accessories_type",
                                @"apparel_type",
                                @"author_artist",
                                @"bag_luggage_type",
                                @"bedding_pattern",
                                @"bed_bath_type",
                                @"books_music_type",
                                @"camera_megapixels",
                                @"camera_type",
                                @"color",
                                @"cost",
                                @"country_of_manufacture",
                                @"created_at",
                                @"custom_design",
                                @"custom_design_from",
                                @"custom_design_to",
                                @"custom_layout_update",
                                @"decor_type",
                                @"description",
                                @"electronic_type",
                                @"fit",
                                @"format",
                                @"frame_style",
                                @"gallery",
                                @"gender",
                                @"gendered",
                                @"genre",
                                @"gift_message_available",
                                @"gift_wrapping_available",
                                @"gift_wrapping_price",
                                @"has_options",
                                @"homeware_style",
                                @"home_decor_type",
                                @"image",
                                @"image_label",
                                @"jewelry_type",
                                @"length",
                                @"lens_type",
                                @"luggage_size",
                                @"luggage_style",
                                @"luggage_travel_style",
                                @"manufacturer",
                                @"material",
                                @"media_gallery",
                                @"meta_description",
                                @"meta_keyword",
                                @"meta_title",
                                @"minimal_price",
                                @"msrp",
                                @"msrp_display_actual_price_type",
                                @"msrp_enabled",
                                @"name",
                                @"necklace_length",
                                @"news_from_date",
                                @"news_to_date",
                                @"occasion",
                                @"options_container",
                                @"page_layout",
                                @"price",
                                @"required_options",
                                @"shoe_size",
                                @"shoe_type",
                                @"short_description",
                                @"size",
                                @"sleeve_length",
                                @"small_image",
                                @"small_image_label",
                                @"special_from_date",
                                @"special_price",
                                @"special_to_date",
                                @"status",
                                @"style",
                                @"tax_class_id",
                                @"thumbnail",
                                @"thumbnail_label",
                                @"updated_at",
                                @"url_key",
                                @"url_path",
                                @"visibility",
                                @"weight",
                                @"width",
                                @"qty",
                                @"min_qty",
                                @"use_config_min_qty",
                                @"is_qty_decimal",
                                @"backorders",
                                @"use_config_backorders",
                                @"min_sale_qty",
                                @"use_config_min_sale_qty",
                                @"max_sale_qty",
                                @"use_config_max_sale_qty",
                                @"is_in_stock",
                                @"notify_stock_qty",
                                @"use_config_notify_stock_qty",
                                @"manage_stock",
                                @"use_config_manage_stock",
                                @"stock_status_changed_auto",
                                @"use_config_qty_increments",
                                @"qty_increments",
                                @"use_config_enable_qty_inc",
                                @"enable_qty_increments",
                                @"is_decimal_divided",
                                @"_links_related_sku",
                                @"_links_related_position",
                                @"_links_crosssell_sku",
                                @"_links_crosssell_position",
                                @"_links_upsell_sku",
                                @"_links_upsell_position",
                                @"_associated_sku",
                                @"_associated_default_qty",
                                @"_associated_position",
                                @"_tier_price_website",
                                @"_tier_price_customer_group",
                                @"_tier_price_qty",
                                @"_tier_price_price",
                                @"_group_price_website",
                                @"_group_price_customer_group",
                                @"_group_price_price",
                                @"_media_attribute_id",
                                @"_media_image",
                                @"_media_lable",
                                @"_media_position",
                                @"_media_is_disabled",
                                @"_custom_option_store",
                                @"_custom_option_type",
                                @"_custom_option_title",
                                @"_custom_option_is_required",
                                @"_custom_option_price",
                                @"_custom_option_sku",
                                @"_custom_option_max_characters",
                                @"_custom_option_sort_order",
                                @"_custom_option_row_title",
                                @"_custom_option_row_price",
                                @"_custom_option_row_sku",
                                @"_custom_option_row_sort",
                                @"_super_products_sku",
                                @"_super_attribute_code",
                                @"_super_attribute_option",
                                @"_super_attribute_price_corr"]];

    NSArray *stores = @[@"default", @"french", @"german"];
    NSArray *categories = @[@"Men", @"Women", @"Accessories", @"Sale", @"Home & Decor"];

    NSInteger i = page * total;
    NSInteger upperBound = i + total;

    while (i < upperBound) {
        i++;
        NSString *sku = [NSString stringWithFormat:@"sku_%05ld", (long)i];
        NSString *store = stores[i % 3];
        NSString *category = categories[i % 5];

        NSString *name = [NSString stringWithFormat:@"item_%06ld", (long)i];
        NSNumber *qty = @(arc4random_uniform(100) + 1);
        NSNumber *taxclass = @((arc4random_uniform(3) + 1) * 2);
        NSNumber *price = @(arc4random_uniform(100) + 1);
        NSNumber *specialPrice = i % 25 ? @(price.doubleValue * arc4random_uniform(100) / 100) : @0;

        NSArray *content = @[sku, // @"sku",
                             store,                    // @"_store",
                             @"Default",               // @"_attribute_set",
                             @"simple",                // @"_type",
                             category,                 // @"_category",
                             @"",                      // @"_root_category",
                             @"base",                  // @"_product_websites",
                             @"",                      // @"accessories_size",
                             @"",                      // @"accessories_type",
                             @"",                      // @"apparel_type",
                             @"",                      // @"author_artist",
                             @"",                      // @"bag_luggage_type",
                             @"",                      // @"bedding_pattern",
                             @"",                      // @"bed_bath_type",
                             @"",                      // @"books_music_type",
                             @"",                      // @"camera_megapixels",
                             @"",                      // @"camera_type",
                             @"",                      // @"color",
                             @"",                      // @"cost",
                             @"",                      // @"country_of_manufacture",
                             @"",                      // @"created_at",
                             @"",                      // @"custom_design",
                             @"",                      // @"custom_design_from",
                             @"",                      // @"custom_design_to",
                             @"",                      // @"custom_layout_update",
                             @"",                      // @"decor_type",
                             name,                     // @"description",
                             @"",                      // @"electronic_type",
                             @"",                      // @"fit",
                             @"",                      // @"format",
                             @"",                      // @"frame_style",
                             @"",                      // @"gallery",
                             @"",                      // @"gender",
                             @"",                      // @"gendered",
                             @"",                      // @"genre",
                             @"",                      // @"gift_message_available",
                             @"",                      // @"gift_wrapping_available",
                             @"",                      // @"gift_wrapping_price",
                             @"0",                     // @"has_options",
                             @"",                      // @"homeware_style",
                             @"",                      // @"home_decor_type",
                             @"",                      // @"image",
                             @"",                      // @"image_label",
                             @"",                      // @"jewelry_type",
                             @"",                      // @"length",
                             @"",                      // @"lens_type",
                             @"",                      // @"luggage_size",
                             @"",                      // @"luggage_style",
                             @"",                      // @"luggage_travel_style",
                             @"",                      // @"manufacturer",
                             @"",                      // @"material",
                             @"",                      // @"media_gallery",
                             @"",                      // @"meta_description",
                             @"",                      // @"meta_keyword",
                             @"",                      // @"meta_title",
                             @"",                      // @"minimal_price",
                             @"",                      // @"msrp",
                             @"Use config",            // @"msrp_display_actual_price_type",
                             @"Use config",            // @"msrp_enabled",
                             name,                     // @"name",
                             @"",                      // @"necklace_length",
                             @"",                      // @"news_from_date",
                             @"",                      // @"news_to_date",
                             @"",                      // @"occasion",
                             @"",                      // @"options_container",
                             @"",                      // @"page_layout",
                             price,                    // @"price",
                             @"0",                     // @"required_options",
                             @"",                      // @"shoe_size",
                             @"",                      // @"shoe_type",
                             name,                     // @"short_description",
                             @"",                      // @"size",
                             @"",                      // @"sleeve_length",
                             @"",                      // @"small_image",
                             @"",                      // @"small_image_label",
                             @"",                      // @"special_from_date",
                             specialPrice,             // @"special_price",
                             @"",                      // @"special_to_date",
                             @"1",                     // @"status",
                             @"",                      // @"style",
                             taxclass,                 // @"tax_class_id",
                             @"",                      // @"thumbnail",
                             @"",                      // @"thumbnail_label",
                             @"",                      // @"updated_at",
                             name,                     // @"url_key",
                             @"",                      // @"url_path",
                             @"4",                     // @"visibility",
                             @"1",                     // @"weight",
                             @"",                      // @"width",
                             qty,                      // @"qty",
                             @"",                      // @"min_qty",
                             @"",                      // @"use_config_min_qty",
                             @"",                      // @"is_qty_decimal",
                             @"",                      // @"backorders",
                             @"",                      // @"use_config_backorders",
                             @"",                      // @"min_sale_qty",
                             @"",                      // @"use_config_min_sale_qty",
                             @"",                      // @"max_sale_qty",
                             @"",                      // @"use_config_max_sale_qty",
                             @"1",                     // @"is_in_stock",
                             @"",                      // @"notify_stock_qty",
                             @"",                      // @"use_config_notify_stock_qty",
                             @"",                      // @"manage_stock",
                             @"",                      // @"use_config_manage_stock",
                             @"",                      // @"stock_status_changed_auto",
                             @"",                      // @"use_config_qty_increments",
                             @"",                      // @"qty_increments",
                             @"",                      // @"use_config_enable_qty_inc",
                             @"",                      // @"enable_qty_increments",
                             @"",                      // @"is_decimal_divided",
                             @"",                      // @"_links_related_sku",
                             @"",                      // @"_links_related_position",
                             @"",                      // @"_links_crosssell_sku",
                             @"",                      // @"_links_crosssell_position",
                             @"",                      // @"_links_upsell_sku",
                             @"",                      // @"_links_upsell_position",
                             @"",                      // @"_associated_sku",
                             @"",                      // @"_associated_default_qty",
                             @"",                      // @"_associated_position",
                             @"",                      // @"_tier_price_website",
                             @"",                      // @"_tier_price_customer_group",
                             @"",                      // @"_tier_price_qty",
                             @"",                      // @"_tier_price_price",
                             @"",                      // @"_group_price_website",
                             @"",                      // @"_group_price_customer_group",
                             @"",                      // @"_group_price_price",
                             @"",                      // @"_media_attribute_id",
                             @"",                      // @"_media_image",
                             @"",                      // @"_media_lable",
                             @"",                      // @"_media_position",
                             @"",                      // @"_media_is_disabled",
                             @"",                      // @"_custom_option_store",
                             @"",                      // @"_custom_option_type",
                             @"",                      // @"_custom_option_title",
                             @"",                      // @"_custom_option_is_required",
                             @"",                      // @"_custom_option_price",
                             @"",                      // @"_custom_option_sku",
                             @"",                      // @"_custom_option_max_characters",
                             @"",                      // @"_custom_option_sort_order",
                             @"",                      // @"_custom_option_row_title",
                             @"",                      // @"_custom_option_row_price",
                             @"",                      // @"_custom_option_row_sku",
                             @"",                      // @"_custom_option_row_sort",
                             @"",                      // @"_super_products_sku",
                             @"",                      // @"_super_attribute_code",
                             @"",                      // @"_super_attribute_option",
                             @""];                     // @"_super_attribute_price_corr"];


        [writer writeLineOfFields:content];
    }
    
    [writer closeStream];
}

#pragma mark - Mage2
+ (void)generateProduct2 {
    for (NSInteger i = 4; i < 16; i++) {
        [self generateProduct2:3000 forPage:i];
    }
}

+ (void)generateProduct2:(NSInteger)total forPage:(NSInteger)page
{
    // Generate empty file
    NSString *fileName = [NSString stringWithFormat:@"productM2%02ld.csv", page];
    NSString *filePath = [self generateFileForName:fileName];

    CHCSVWriter *writer = [[CHCSVWriter alloc] initForWritingToCSVFile:filePath];
    [writer writeLineOfFields:@[@"sku",
                                @"store_view_code",
                                @"attribute_set_code",
                                @"product_type",
                                @"categories",
                                @"product_websites",
                                @"name",
                                @"description",
                                @"short_description",
                                @"weight",
                                @"product_online",
                                @"tax_class_name",
                                @"visibility",
                                @"price",
                                @"special_price",
                                @"special_price_from_date",
                                @"special_price_to_date",
                                @"url_key",
                                @"meta_title",
                                @"meta_keywords",
                                @"meta_description",
                                @"base_image",
                                @"base_image_label",
                                @"small_image",
                                @"small_image_label",
                                @"thumbnail_image",
                                @"thumbnail_image_label",
                                @"swatch_image",
                                @"swatch_image_label",
                                @"created_at",
                                @"updated_at",
                                @"new_from_date",
                                @"new_to_date",
                                @"display_product_options_in",
                                @"map_price",
                                @"msrp_price",
                                @"map_enabled",
                                @"gift_message_available",
                                @"custom_design",
                                @"custom_design_from",
                                @"custom_design_to",
                                @"custom_layout_update",
                                @"page_layout",
                                @"product_options_container",
                                @"msrp_display_actual_price_type",
                                @"country_of_manufacture",
                                @"additional_attributes",
                                @"qty",
                                @"out_of_stock_qty",
                                @"use_config_min_qty",
                                @"is_qty_decimal",
                                @"allow_backorders",
                                @"use_config_backorders",
                                @"min_cart_qty",
                                @"use_config_min_sale_qty",
                                @"max_cart_qty",
                                @"use_config_max_sale_qty",
                                @"is_in_stock",
                                @"notify_on_stock_below",
                                @"use_config_notify_stock_qty",
                                @"manage_stock",
                                @"use_config_manage_stock",
                                @"use_config_qty_increments",
                                @"qty_increments",
                                @"use_config_enable_qty_inc",
                                @"enable_qty_increments",
                                @"is_decimal_divided",
                                @"website_id",
                                @"related_skus",
                                @"related_position",
                                @"crosssell_skus",
                                @"crosssell_position",
                                @"upsell_skus",
                                @"upsell_position",
                                @"additional_images",
                                @"additional_image_labels",
                                @"hide_from_product_page",
                                @"custom_options",
                                @"bundle_price_type",
                                @"bundle_sku_type",
                                @"bundle_price_view",
                                @"bundle_weight_type",
                                @"bundle_values",
                                @"bundle_shipment_type",
                                @"configurable_variations",
                                @"configurable_variation_labels",
                                @"associated_skus"]];

    // Pre-defines
    NSDictionary *webSiteCodes = @{@"1" : @"base",
                                   @"6" : @"asia",
                                   @"2" : @"usa",
                                   @"4" : @"eu"};
    NSArray *taxClasses = @[@"Taxable Goods", @"Shipping", @"Tax Exempt"];
    NSInteger i = page * total;
    NSInteger upperBound = i + total;

    while (i < upperBound) {
        i++;
        NSString *sku = [NSString stringWithFormat:@"sku%05ld", (long)i];
        NSString *websiteId = webSiteCodes.allKeys[i % webSiteCodes.count];
        NSString *website   = webSiteCodes[websiteId];
        NSString *desc      = [self randomStringForLength:100];
        NSNumber *productOnline = @((i % 2) + 1);

        NSString *name = [NSString stringWithFormat:@"product%06ld", (long)i];
        NSNumber *qty = @(arc4random_uniform(100) + 1);
        NSNumber *taxclass = taxClasses[i % taxClasses.count];
        NSString *visibility = (i % 2 ? @"Catalog" : @"Search");
        NSNumber *price = @(arc4random_uniform(100) + 1);
        NSNumber *specialPrice = i % 25 ? @(price.doubleValue * arc4random_uniform(100) / 100) : @0;

        NSArray *content = @[sku,
                             @"",                 // @"store_view_code",
                             @"Default",          // @"attribute_set_code",
                             @"simple",           // @"product_type",
                             @"Default Category", // @"categories",
                             website,             // @"product_websites",
                             name,                // @"name",
                             desc,                // @"description",
                             @"",                 // @"short_description",
                             @"1",                // @"weight",
                             productOnline,       // @"product_online",
                             taxclass,            // @"tax_class_name",
                             visibility,          // @"visibility",
                             price,               // @"price",
                             specialPrice,        // @"special_price",
                             @"",                 // @"special_price_from_date",
                             @"",                 // @"special_price_to_date",
                             name,                // @"url_key",
                             @"",                 // @"meta_title",
                             @"",                 // @"meta_keywords",
                             @"",                 // @"meta_description",
                             @"",                 // @"base_image",
                             @"",                 // @"base_image_label",
                             @"",                 // @"small_image",
                             @"",                 // @"small_image_label",
                             @"",                 // @"thumbnail_image",
                             @"",                 // @"thumbnail_image_label",
                             @"",                 // @"swatch_image",
                             @"",                 // @"swatch_image_label",
                             @"",                 // @"created_at",
                             @"",                 // @"updated_at",
                             @"",                 // @"new_from_date",
                             @"",                 // @"new_to_date",
                             @"",                 // @"display_product_options_in",
                             @"",                 // @"map_price",
                             @"",                 // @"msrp_price",
                             @"",                 // @"map_enabled",
                             @"",                 // @"gift_message_available",
                             @"",                 // @"custom_design",
                             @"",                 // @"custom_design_from",
                             @"",                 // @"custom_design_to",
                             @"",                 // @"custom_layout_update",
                             @"",                 // @"page_layout",
                             @"",                 // @"product_options_container",
                             @"Use config",       // @"msrp_display_actual_price_type",
                             @"",                 // @"country_of_manufacture",
                             @"",                 // @"additional_attributes",
                             qty,                 // @"qty",
                             @"0",                // @"out_of_stock_qty",
                             @"1",                // @"use_config_min_qty",
                             @(i % 2),            // @"is_qty_decimal",
                             @(i % 2 ? 2 : 0),    // @"allow_backorders",
                             @"1",                // @"use_config_backorders",
                             @"1",                // @"min_cart_qty",
                             @"1",                // @"use_config_min_sale_qty",
                             @"1000",             // @"max_cart_qty",
                             @"1",                // @"use_config_max_sale_qty",
                             @(i % 2),            // @"is_in_stock",
                             @"",                 // @"notify_on_stock_below",
                             @"",                 // @"use_config_notify_stock_qty",
                             @"1",                // @"manage_stock",
                             @"1",                // @"use_config_manage_stock",
                             @"",                 // @"use_config_qty_increments",
                             @"",                 // @"qty_increments",
                             @"",                 // @"use_config_enable_qty_inc",
                             @"",                 // @"enable_qty_increments",
                             @"",                 // @"is_decimal_divided",
                             websiteId,           // @"website_id",
                             @"",                 // @"related_skus",
                             @"",                 // @"related_position",
                             @"",                 // @"crosssell_skus",
                             @"",                 // @"crosssell_position",
                             @"",                 // @"upsell_skus",
                             @"",                 // @"upsell_position",
                             @"",                 // @"additional_images",
                             @"",                 // @"additional_image_labels",
                             @"",                 // @"hide_from_product_page",
                             @"",                 // @"custom_options",
                             @"",                 // @"bundle_price_type",
                             @"",                 // @"bundle_sku_type",
                             @"",                 // @"bundle_price_view",
                             @"",                 // @"bundle_weight_type",
                             @"",                 // @"bundle_values",
                             @"",                 // @"bundle_shipment_type",
                             @"",                 // @"configurable_variations",
                             @"",                 // @"configurable_variation_labels",
                             @""];                // @"associated_skus"

        [writer writeLineOfFields:content];
    }
    
    [writer closeStream];
}

@end
